name: Deploy Web App

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
      - '.github/workflows/deploy-web.yml'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: cd web && npm ci
      
      - name: Build
        run: cd web && npm run build
        env:
          REACT_APP_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          REACT_APP_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          REACT_APP_EVENTBRITE_API_KEY: ${{ secrets.EVENTBRITE_API_KEY }}
          REACT_APP_TRIPADVISOR_API_KEY: ${{ secrets.TRIPADVISOR_API_KEY }}
      
      # Deploy to Vercel (example)
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./web
          vercel-args: '--prod'
